### ISSUE TITLE
glassdoor link gives me an error

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/careers-answering-non-technical-interview-questions#5]
When I click on the glassdoor link at the bottom of this lesson, I get an error "You do not have access to [that] lesson," and am redirected back to this lesson.

Thank you.

**Comment by maxwellbenton** [comment]
Hi @ValerieHMoore,

Thank you for reporting this. I've updated the link to glassdoor and confirmed it works in Learn and GitHub, so I believe this issue is resolved.

Thank you!
