### ISSUE TITLE
No access to Google Drive link

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/careers-answering-non-technical-interview-questions#6]
When I click on the last link on the page, "30 Behavioral Interview Questions to Identify High-Potential Candidates," I'm taken to a Google Drive link that says "You need permission." I clicked on the Request access button; was that the intention for this lesson?

Thank you.

**Comment by maxwellbenton** [comment]
Hi @ValerieHMoore,

I've tested this link but unfortunately was unable to replicate the issue you experienced. The document may have been updated since this issue as it now opens even in incognito mode. Since it is currently working, I am going to close this issue.

Thank you!
